[project]
authors = ["Chaebeom Sheen <cauchybs@snu.ac.kr>"]
channels = ["conda-forge", "bioconda"]
description = "Add a short description here"
name = "python-linearpartition"
platforms = ["linux-64"]
version = "0.3.0"

[tasks]

[dependencies]
python = "3.10"
pip = ">=24.2,<25"

[environments]
test-old = ["test-old"]
test-now = ["test-now"]
test-new = ["test-new"]

[feature.test-old.pypi-dependencies]
linearpartition-unofficial = "==0.2.0"

[feature.test-now.pypi-dependencies]
linearpartition-unofficial = "==0.3.0"

[feature.test-new.pypi-dependencies]
ViennaRNA = "==2.6.4"

[pypi-dependencies]
numpy = "==1.26.4"

